before:
  hooks:
    - go mod download
builds:
  - 
    id: tunl
    main: ./cmd/main.go
    binary: tunl
    ldflags:
      - -s
      - -w
      - -X github.com/pjvds/tunl/pkg/version.BuildDate={{.Date}}
      - -X github.com/pjvds/tunl/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/pjvds/tunl/pkg/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    gobinary: "go1.16beta1"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - tunl
    image_templates:
    - "tunl/tunl:latest"
    - "tunl/tunl:{{ .Tag }}"
    - "tunl/tunl:v{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/pjvds/tunl/tunl:latest"
    - "docker.pkg.github.com/pjvds/tunl/tunl:{{ .Tag }}"
    - "docker.pkg.github.com/pjvds/tunl/tunl:v{{ .Major }}.{{ .Minor }}"
    extra_files:

brews:
  -
    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support atm only one 32-bit version.
    # Default is 6 for all artifacts or each id if there a multiple versions.
    goarm: 6

    tap:
      owner: pjvds
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Pieter Joost van de Sande
      email: pj@born2code.net

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://tunl.es/"

    # Your app's description.
    # Default is empty.
    description: "With Tunl you can expose services on your localhost to the public via a fast and secure tunnel."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

#snapcrafts:
#  -
#    id: tunl
#    publish: true
#    summary: Expose your localhost to the public
#    description: With Tunl you can expose services on your localhost to the public via a fast and secure tunnel.
#    grade: devel
#    confinement: devmode
#    license: Apache-2.0
#    base: bare
#    apps:
#      tunl:
#        plugs: 
#        - network
archives:
  - 
    id: tunl
    builds:
      - tunl
    files: 
      - LICENSE
      - autocomplete/**/*
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
